import { AnchorProvider, BN, Program, web3 } from 'https://esm.sh/@coral-xyz/anchor@0.30.1?bundle';

const PROGRAM_ID = new web3.PublicKey('9Uf52hSPJPDqDj7QFqL5dKmdJseU1pRtzL8oNQGeDxrP');
const MIN_BET_SOL = 0.1;
const connection = new web3.Connection(web3.clusterApiUrl('devnet'), 'confirmed');
const elements = { connect: document.getElementById('connectWallet'), bet: document.getElementById('betButton'), message: document.getElementById('actionMessage'), timer: document.getElementById('timer'), progress: document.getElementById('timerProgress'), round: document.getElementById('roundNumber'), state: document.getElementById('roundState'), players: document.getElementById('playersCount'), pot: document.getElementById('potAmount'), settleCountdown: document.getElementById('settleCountdown'), walletModal: document.getElementById('walletModal'), walletMessage: document.getElementById('walletMessage'), phantomStatus: document.getElementById('phantomStatus'), solflareStatus: document.getElementById('solflareStatus') };
let walletPublicKey = null;
let program = null;
let currentRoundId = null;
let clockOffsetMs = 0;
let selectedBetSol = MIN_BET_SOL;
const localClockEpoch = Date.now() - performance.now();
const idl = { address: PROGRAM_ID.toBase58(), metadata: { name: 'minuttery', version: '0.1.0', spec: '0.1.0' }, instructions: [{ name: 'placeBet', discriminator: [222, 62, 67, 220, 63, 166, 126, 33], accounts: [{ name: 'player', writable: true, signer: true }, { name: 'round', writable: true }, { name: 'systemProgram', address: web3.SystemProgram.programId.toBase58() }], args: [{ name: 'roundId', type: 'i64' }, { name: 'amount', type: 'u64' }, { name: 'seed', type: { array: ['u8', 32] } }] }], accounts: [{ name: 'RoundState', discriminator: [153, 242, 39, 64, 102, 34, 239, 11] }], types: [{ name: 'RoundState', type: { kind: 'struct', fields: [{ name: 'roundId', type: 'i64' }, { name: 'participantsCount', type: 'u32' }, { name: 'totalPot', type: 'u64' }, { name: 'status', type: { defined: { name: 'RoundStatus' } } }, { name: 'initiator', type: 'pubkey' }, { name: 'initiatorRent', type: 'u64' }, { name: 'winner', type: 'pubkey' }, { name: 'players', type: { vec: { defined: { name: 'PlayerEntry' } } } }] } }, { name: 'RoundStatus', type: { kind: 'enum', variants: [{ name: 'Open' }, { name: 'Resolved' }, { name: 'Expired' }] } }, { name: 'PlayerEntry', type: { kind: 'struct', fields: [{ name: 'wallet', type: 'pubkey' }, { name: 'seed', type: { array: ['u8', 32] } }, { name: 'amount', type: 'u64' }, { name: 'refunded', type: 'bool' }] } }] };
function currentRound() { return Math.floor(Date.now() / 1000 / 60); }
function roundPda(roundId) { return web3.PublicKey.findProgramAddressSync([new TextEncoder().encode('round'), new BN(roundId).toArrayLike(Uint8Array, 'le', 8)], PROGRAM_ID)[0]; }
function setMessage(message, isError = false) { elements.message.textContent = message; elements.message.style.color = isError ? '#ff7575' : ''; }
function syncedNow() { return localClockEpoch + performance.now() + clockOffsetMs; }
function updateClock() { const preciseNow = syncedNow(); const elapsedInRound = ((preciseNow % 60000) + 60000) % 60000; const seconds = Math.floor(elapsedInRound / 1000); const centiseconds = Math.floor((elapsedInRound % 1000) / 10); const secondsUntilSettlementExpiry = Math.max(0, 85 - seconds); elements.timer.textContent = `00:${String(seconds).padStart(2, '0')}:${String(centiseconds).padStart(2, '0')}`; elements.settleCountdown.textContent = secondsUntilSettlementExpiry; elements.progress.style.width = `${(elapsedInRound / 60000) * 100}%`; const roundId = Math.floor(preciseNow / 60000); elements.round.textContent = roundId; elements.bet.disabled = seconds >= 55; elements.bet.querySelector('span').textContent = walletPublicKey ? 'Bet and go' : 'Connect your wallet'; if (seconds >= 55) { elements.state.textContent = 'betting closed'; setMessage('The next round starts in a few seconds'); } else if (!walletPublicKey) { elements.state.textContent = 'round open'; setMessage('Connect your wallet to join this round'); } if (roundId !== currentRoundId) { currentRoundId = roundId; loadRound(); } requestAnimationFrame(updateClock); }
async function syncClock() { try { const slot = await connection.getSlot('processed'); const blockTime = await connection.getBlockTime(slot); if (blockTime) clockOffsetMs = (blockTime * 1000) - (localClockEpoch + performance.now()); } catch { /* Keep the local clock if RPC time is unavailable. */ } }
async function loadRound() { elements.players.textContent = '--'; elements.pot.textContent = '--'; try { if (!program) return; const round = await program.account.roundState.fetch(roundPda(currentRoundId)); elements.players.textContent = round.participantsCount.toString(); elements.pot.textContent = (Number(round.totalPot.toString()) / web3.LAMPORTS_PER_SOL).toFixed(2); } catch { elements.players.textContent = '0'; elements.pot.textContent = '0.00'; } }
function getPhantom() { return window.phantom?.solana || (window.solana?.isPhantom ? window.solana : null); }
function openWalletModal() { elements.walletMessage.textContent = ''; elements.phantomStatus.textContent = getPhantom() ? 'Ready to connect' : 'Open in Phantom app'; elements.solflareStatus.textContent = window.solflare?.isSolflare ? 'Ready to connect' : 'Open in Solflare app'; elements.walletModal.hidden = false; }
function closeWalletModal() { elements.walletModal.hidden = true; }
async function connectWallet() { openWalletModal(); }
async function connectProvider(wallet) { try { const response = await wallet.connect(); walletPublicKey = response.publicKey; const provider = new AnchorProvider(connection, wallet, { commitment: 'confirmed' }); program = new Program(idl, provider); elements.connect.textContent = `${walletPublicKey.toBase58().slice(0, 4)}...${walletPublicKey.toBase58().slice(-4)}`; closeWalletModal(); setMessage('Wallet connected. The round is ready.'); await loadRound(); } catch (error) { elements.walletMessage.textContent = error.message || 'Could not connect wallet'; } }
async function placeBet() { if (!program || !walletPublicKey) return connectWallet(); elements.bet.disabled = true; elements.bet.querySelector('span').textContent = 'Confirming...'; try { const seed = Array.from(crypto.getRandomValues(new Uint8Array(32))); await program.methods.placeBet(new BN(currentRoundId), new BN(selectedBetSol * web3.LAMPORTS_PER_SOL), seed).accounts({ player: walletPublicKey, round: roundPda(currentRoundId), systemProgram: web3.SystemProgram.programId }).rpc(); setMessage('Bet confirmed. May luck find you.'); await loadRound(); } catch (error) { setMessage(error.message || 'Transaction could not be completed', true); } updateClock(); }
elements.connect.addEventListener('click', connectWallet); elements.bet.addEventListener('click', placeBet); document.querySelectorAll('.bet-preset').forEach((button) => button.addEventListener('click', () => { selectedBetSol = Number(button.dataset.amount); document.querySelectorAll('.bet-preset').forEach((item) => item.classList.remove('is-selected')); button.classList.add('is-selected'); })); document.getElementById('closeWalletModal').addEventListener('click', closeWalletModal); elements.walletModal.addEventListener('click', (event) => { if (event.target === elements.walletModal) closeWalletModal(); }); document.querySelector('[data-wallet="phantom"]').addEventListener('click', () => { const phantom = getPhantom(); if (phantom) connectProvider(phantom); else { elements.walletMessage.textContent = 'Open this page in the Phantom app browser to connect.'; elements.phantomStatus.textContent = 'Open in Phantom app'; window.location.href = `https://phantom.app/ul/browse/${encodeURIComponent(window.location.href)}`; } }); document.querySelector('[data-wallet="solflare"]').addEventListener('click', () => { if (window.solflare?.isSolflare) connectProvider(window.solflare); else elements.walletMessage.textContent = 'Open this page in the Solflare app browser to connect.'; }); window.solana?.on('disconnect', () => { walletPublicKey = null; program = null; elements.connect.textContent = 'Connect wallet'; }); document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'visible') syncClock(); }); currentRoundId = Math.floor(syncedNow() / 60000); updateClock(); syncClock(); setInterval(syncClock, 60000); loadRound();
